apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: code-server
  name: code-server
spec:
  ports:
  - port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    run: code-server
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: code-server
  name: code-server
spec:
  containers:
  - image: ghcr.io/linuxserver/code-server
    name: code-server
    env:
    - name: PASSWORD
      value: h5WqrvVY1LQ=      
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

